### ISSUE TITLE
Running in xhyve/docker

### ISSUE THREAD

**Issue by GeorgeLyon** [ixy-languages/ixy.swift#1]
I saw this mentioned in the ccc keynote and was a little suspicious about claims of poor performance, especially after seeing the flame graphs and the exorbitant amount of time spent in ARC. Glancing at the code I see much unnecessary use of classes. I'm confident that if I dug into it, I could increase performance substantially. 

While it won't give accurate performance numbers, can you provide some guidance for running this in either xhyve or docker? I'm on a MacBook, and that way I could at least run the code.

**Comment by emmericp** [comment]
There's unfortunately no hypervisor that supports emulating a 82599 (for good reason), but even if there was one, it would be pointless for performance tests because the hypervisor would be the bottleneck. We intentionally target real hardware only here (some of our other drivers also support virtio NICs, but the perforamnce results there are not comparable).


Please keep in mind that we are aiming for idiomatic implementations in all languages, so we want code that looks like code that was written for Swift and not some collection of hacks to make it as fast as possible.

But we are happy to test any pull requests on our testbed :)

**Comment by GeorgeLyon** [comment]
I understand it would be meaningless for performance, but you could at least test that a certain number of packets now results in N less calls to retain/release (and then submit that patch to run on hardware). Is there a way I can run the code to test just this very limited metric, while still verifying the correctness of the code?

As for things being "idiomatic", that's a bit of a qualitative argument. The Swift team at apply has long been pushing structs and protocol-oriented programming as the way to get the best out of Swift. Making something simple like a network driver with these concepts should be very possible, and much more performant than an Objective-C or Java-like class-based implementation.

**Comment by emmericp** [comment]
Unfortunately the 82599 isn't supported by any hypervisor/emulator that I'm aware of. Despite this it was the best target hardware for our project for various reasons.

Happy to test any pull requests on real hardware for you
